# Generated by Django 6.0.3 on 2026-05-06 17:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0002_clientprofile_alter_review_client_jobrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientprofile',
            name='address',
            field=models.CharField(blank=True, help_text='Dirección para recibir el servicio', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='bio',
            field=models.TextField(blank=True, help_text='Breve descripción de su experiencia en el trabajo', null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='workers', to='servicios.category'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='full_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='phone_number',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
    ]
