# Generated by Django 6.0.3 on 2026-05-08 06:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0004_alter_workerprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'verbose_name': 'Solicitud de Trabajo', 'verbose_name_plural': 'Solicitudes de Trabajo'},
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='address_reference',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Referencia de ubicación'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='client',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solicitudes_enviadas', to='servicios.clientprofile'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='description',
            field=models.TextField(help_text='¿Qué necesita que el trabajador haga?', verbose_name='Descripción del trabajo'),
        ),
        migrations.AlterField(
            model_name='jobrequest',
            name='worker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='trabajos_recibidos', to='servicios.workerprofile'),
        ),
    ]
