# Generated by Django 6.0.3 on 2026-05-10 03:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0006_alter_workerprofile_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='jobrequest',
            options={'ordering': ['-created_at'], 'verbose_name': 'Solicitud de Trabajo', 'verbose_name_plural': 'Solicitudes de Trabajo'},
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='evidencia_foto',
            field=models.ImageField(blank=True, null=True, upload_to='solicitudes/', verbose_name='Foto del problema (Opcional)'),
        ),
        migrations.AlterField(
            model_name='workerprofile',
            name='service_area',
            field=models.CharField(max_length=100),
        ),
    ]
