# Generated by Django 6.0.3 on 2026-05-11 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicios', '0008_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobrequest',
            name='client_confirmation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='jobrequest',
            name='worker_confirmation',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientprofile',
            name='municipality',
            field=models.CharField(max_length=100, verbose_name='Municipio'),
        ),
    ]
